// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Account
{
    public string UserId { get; set; }

    public string UserName { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public bool? IsActive { get; set; }

    public int? RoleId { get; set; }

    public string ProfilePicture { get; set; }

    public virtual ICollection<ChatHistory> ChatHistoryReceivers { get; set; } = new List<ChatHistory>();

    public virtual ICollection<ChatHistory> ChatHistorySenders { get; set; } = new List<ChatHistory>();

    public virtual Role Role { get; set; }
}