// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ChatHistory
{
    public int ChatId { get; set; }

    public string SenderId { get; set; }

    public string ReceiverId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Content { get; set; }

    public virtual Account Receiver { get; set; }

    public virtual Account Sender { get; set; }
}