// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Destination
{
    public string DestinationId { get; set; }

    public string DestinationName { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public double? Rate { get; set; }

    public string CategoryId { get; set; }

    public string Ward { get; set; }

    public string Status { get; set; }

    public string DistrictId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Category Category { get; set; }

    public virtual District District { get; set; }

    public virtual ICollection<OpeningHour> OpeningHours { get; set; } = new List<OpeningHour>();
}