// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Destination
{
    public int DestinationId { get; set; }

    public string DestinationName { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public double? Rate { get; set; }

    public int? CategoryId { get; set; }

    public string Ward { get; set; }

    public string Status { get; set; }

    public int? DistrictId { get; set; }

    public virtual Category Category { get; set; }

    public virtual District District { get; set; }

    public virtual ICollection<OpeningHour> OpeningHours { get; set; } = new List<OpeningHour>();
}