// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class District
{
    public int DistrictId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? CityId { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<Destination> Destinations { get; set; } = new List<Destination>();
}